### ISSUE TITLE
Benchmark?

### ISSUE THREAD

**Issue by denji** [shdnx/dangless-malloc#1]
Other refs
* https://github.com/rampantpixels/rpmalloc-benchmark
* https://github.com/SergeyMakeev/smmalloc#performance
* https://github.com/rampantpixels/rpmalloc

**Comment by shdnx** [comment]
Thank you for the benchmarking suggestions!

Dangless is not a regular memory allocator, and as such, its performance has to be measured differently. The main source of overhead with Dangless is the increased TLB miss read, the overhead introduced by the virtualization layer, and the additional pagetables necessary to maintain the shadow mappings. Measuring these is a bit more involved than just benchmarking allocator performance.

That said, benchmarking definitely should be a bigger focus, and will likely be the main topic of further research after my thesis.
