### ISSUE TITLE
Having and issue while compiling

### ISSUE THREAD

**Issue by SpiralBL0CK** [shdnx/dangless-malloc#2]
after registering as git submodules , and applying the dune-ix-vmcallprehook.old.patch when i run sudo make i get the following errors
![Screenshot from 2019-11-23 19-08-53](https://user-images.githubusercontent.com/25670930/69482488-bbc3bc00-0e24-11ea-8fde-8345ee7ca2da.png)

**Comment by shdnx** [comment]
Don't apply `dune-ix-vmcallprehook.old.patch` - as the name indicates, it's an old version of the patch, and frankly, should have been removed long ago.

You want to apply the following patches:
 - `dune-ix-guestppages.patch`
 - `dune-ix-vmcallprehook.patch`
 - `dune-ix-nosigterm.patch`

Please see the `README` for precise instructions.
